name: bmsce
description: A new Flutter project on BMS College that gives solutions to many problems.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_database: any
  sqflite: 0.11.1
  path_provider: 0.4.1
  firebase_storage: any
  tuple: ^1.0.2
  firebase_auth: any
  google_sign_in: ^3.0.4
  charts_flutter: ^0.4.0
  material_search: ^0.2.8
  firebase_dynamic_links: ^0.1.0+1
  share: ^0.5.3
  shared_preferences: ^0.4.2
  firebase_messaging: any
  url_launcher: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
  - assets/images/bmsce_logo.png
  - assets/images/bmsce_logo_inner.png
  - assets/images/bmsce_logo_outer_2.png
  - assets/images/detective_duck.png
  - assets/images/minion_sad.png
  - assets/images/bmsce_tree.jpg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
     - family: OpenSans
       fonts:
         - asset: assets/fonts/OpenSans-Light.ttf
         - asset: assets/fonts/OpenSans-Regular.ttf
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
     - family: RobotoSlab
       fonts:
         - asset: assets/fonts/RobotoSlab-Bold.ttf
         - asset: assets/fonts/RobotoSlab-Light.ttf
     - family: Ubuntu
       fonts:
         - asset: assets/fonts/Ubuntu-LightItalic.ttf
           style: italic
         - asset: assets/fonts/Ubuntu-Regular.ttf
           style: normal
     - family: UbuntuMono
       fonts:
         - asset: assets/fonts/UbuntuMono-Regular.ttf


         #          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
